FROM ubuntu:24.04 AS base
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv \
    redis openssh-server


FROM base AS venv
WORKDIR /app
RUN python3 -m venv venv
RUN . venv/bin/activate && pip install \
    'flask[async]' gunicorn redis cryptography httpx \
    'flask-openapi3[swagger, rapipdf, rapidoc]' kubernetes

FROM venv AS app
COPY service.tgz stu-site.tgz adm-site.tgz /tmp/
COPY yatcc-se/YatCC-SE /YatCC-SE

WORKDIR /app
RUN tar -xzf /tmp/service.tgz && \
    mkdir -p adm-site stu-site && \
    tar -xzf /tmp/adm-site.tgz -C adm-site && \
    tar -xzf /tmp/stu-site.tgz -C stu-site && \
    rm -rf /tmp/*
COPY yatcc-se/config.py /app/


VOLUME ["/io"]
EXPOSE 22 5001 5002
ENTRYPOINT ["/YatCC-SE"]
