#!/app/venv/bin/python3
"""代码空间核心"""

import sys
from argparse import ArgumentParser

argp = ArgumentParser(description=__doc__)
argp.add_argument("--sleep", action="store_true", help="sleep infinity")
argp.add_argument("--log-level", type=int)

ARGS = argp.parse_args()
ARG_SLEEP: bool = ARGS.sleep
ARG_LOG_LEVEL: int | None = ARGS.log_level


# ==================================================================================== #

sys.path.insert(0, "/app")
import base
import base.entry
import base.logger
from codespace import CONFIG, entry

log_level = ARG_LOG_LEVEL if ARG_LOG_LEVEL is not None else base.logger.INFO


async def nop():
    pass


if ARG_SLEEP:
    co = base.entry.main(nop, nop, "CODESPACE", CONFIG.log_dir, log_level=log_level)
else:
    co = base.entry.main(
        entry.start, entry.stop, "CODESPACE", CONFIG.log_dir, log_level=log_level
    )
exit(base.RUNNER.run(co))
