/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountPanel: typeof import('./src/components/home/account/AccountPanel.vue')['default']
    AccountProfile: typeof import('./src/components/home/account/AccountProfile.vue')['default']
    CodespaceList: typeof import('./src/components/home/codespace/CodespaceList.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ListContainer: typeof import('./src/components/common/ListContainer.vue')['default']
    MultiAddPanel: typeof import('./src/components/home/student/StudentAdd/MultiAddPanel.vue')['default']
    ResultDialog: typeof import('./src/components/common/ResultDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleAddPanel: typeof import('./src/components/home/student/StudentAdd/SingleAddPanel.vue')['default']
    SpaceInput: typeof import('./src/components/common/SpaceInput.vue')['default']
    StudentAdd: typeof import('./src/components/home/student/StudentAdd/StudentAdd.vue')['default']
    StudentDetail: typeof import('./src/components/home/student/StudentList/StudentDetail/StudentDetail.vue')['default']
    StudentList: typeof import('./src/components/home/student/StudentList/StudentList.vue')['default']
    TaskerAdd: typeof import('./src/components/home/tasker/TaskerAdd.vue')['default']
    TaskerDetails: typeof import('./src/components/home/tasker/TaskerDetails.vue')['default']
    TaskerList: typeof import('./src/components/home/tasker/TaskerList.vue')['default']
    TimeInput: typeof import('./src/components/common/TimeInput.vue')['default']
  }
}
