apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codespace-workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codespace-userdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codespace-extensions-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codespace-io-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: codespace-ssh-keys
type: Opaque
data:
  # 你需要将 SSH 密钥进行 base64 编码后填入
  # echo -n "your-private-key-content" | base64
  id_rsa: ""
  id_rsa.pub: ""
  authorized_keys: ""
